### ISSUE TITLE
Does the effectiveness of self-reflection depend on the participation of ground-truth answers?

### ISSUE THREAD

**Issue by songxiaoshuai** [matthewrenze/self-reflection#1]
Hi, thank you for your work on self-reflection: Self-Reflection in LLM Agents: Effects on Problem-Solving Performance!
﻿I am able to successfully replicate the experimental phenomena described in the paper. However, I notice that the effectiveness of self-reflection in the experiment highly depends on whether the ground-truth answer is incorporated into the reflection generation process. Although the other reflection types besides Unredacted implement a masking approach for the ground-truth answer, it still seems insufficient to prevent information about the ground-truth answer from leaking into the reflection content. For example, reflections may deliberately interpret the correct option.
﻿When I attempt to remove the ground-truth answer from the reflection process— by commenting out these lines in 2_reflect_on_solutions.py:
﻿```
user_prompt += "\n --- \n"
user_prompt += f"Correct Answer: {ground_truth_answer}\n"
﻿```
I find that the effectiveness of all reflections decreases significantly and does not provide effective improvement compared to the baseline and retry.
﻿Thank you once again for taking the time to read my question. I look forward to your response.

**Comment by matthewrenze** [comment]
@songxiaoshuai, thank you for your question and your feedback.

Yes, you are correct. Removing the correct answers from the reflection step will decrease the performance of the models compared to providing correct answers. However, you should still see a statistically significant increase in performance for most self-reflection types, even without being provided the correct answer. In addition, the performance should (generally) increase as a function of the amount of information the reflection hint captures (e.g., Composite > Explanation > Keywords).

To demonstrate, I re-ran a subset of the experiment using GPT-3.5 and GPT-4 with 100 questions and all reflection types. I ran the mini-experiment once with the correct answers being provided and a second time without the correct answer being provided. To do so, I removed the line of code you indicated and modified the few-shot examples so that the prompt does not anticipate being given the correct answer.

Here are the results:

**GPT-3.5 with correct answers**
![gpt-35-with-answers](https://github.com/user-attachments/assets/8e79e959-3f41-4fec-833a-c9c25bae196e)

**GPT-3.5 without correct answers**
![gpt-35-no-answers](https://github.com/user-attachments/assets/4b882681-cfa9-405f-90b1-75f4c11852bc)

**GPT-4 with correct answers**
![gpt-4-with-answers](https://github.com/user-attachments/assets/f610d690-b827-43cd-bb94-74a458a80198)

**GPT-4 without correct answers**
![gpt-4-no-answers](https://github.com/user-attachments/assets/21f07554-b956-42af-85e2-97fe8127f762)

By making these modifications, the LLM is being asked to _both_ determine which of the remaining multiple-choice answers is the correct answer _and_ to reflect on its chain of thought to identify errors and generate reflection hints to help it improve its performance in the future. This is obviously more difficult for the LLM than just reflecting on its mistakes once it knows what the correct answer is. So, there is an expected decrease in performance.

Conceptually, my version of the experiment is similar to taking a multiple-choice quiz, getting a problem wrong, and being shown the correct answer so that you can learn where you made your mistake to provide yourself with guidance on how to avoid similar mistakes in the future.

The version of the experiment you're suggesting is similar to taking a multiple-choice quiz and only being told you got the answer wrong but not knowing which of the remaining answers is the correct answer. So, you would need to rework the problem to identify which answer is correct first, and then (based on which answer you now believe to be correct, but may not actually be the correct answer), you try to determine where your mistakes were. Finally, using that info, you provide yourself with guidance on how to avoid similar mistakes in the future.

Both approaches seem reasonable to me. However, I intentionally chose to focus only on the benefits of self-reflection -- not the LLMs ability to infer the correct answer from the remaining answers _and_ the benefits of self-reflection. This decision was also partially because some of the LLMs are not very good at determining where they made a mistake without being shown the correct answer first.

Regarding information leakage, yes, you are correct that providing the correct answer to the LLM increases the likelihood of leaking information about the correct answer to LLM while re-answering the question. This is especially the case with the Instructions, Explanation, Solution, and Composite self-reflection types. This is why I performed a greedy redaction of the correct answer and provided the unredacted self-reflection -- as an upper bound on performance with fully leaked answers.

Given this, I agree that it would have been best to perform the entire experiment both with and without the correct answer being provided -- for comparison. However, running the experiment once was rather expensive and took several days. So, that would easily double the cost and time to re-run with both experimental treatments. In addition, it would significantly increase the complexity of the paper to present and explain both sets of results. 

However, based on your feedback, it might be beneficial for future readers if I were to add a note about this. I will likely be performing an update of the paper soon (as it's currently in peer review). So, I will add a note about this when the time comes to do a final revision before publication.

Thanks again for reaching out. Hopefully, this answers your question. Please let me know if you have any additional questions or concerns. 

Thanks!

Matthew

**Comment by songxiaoshuai** [comment]
Thank you for your quick reply. It has effectively resolved my questions, and I appreciate your assistance.😊
